carts:
  router:
    home: '35:0'
    destinations:
      '35:0':
        name: Main station
        short: white
      '35:1':
        name: Sheep farm
        short: orange
      '35:2':
        name: Magenta station
        short: magenta
      '35:7':
        name: Gray station
        short: gray
      '35:14':
        name: Red station
        short: red
